version: '3.8'
services:
        api:
                build:
                        context: .
                        dockerfile: apps/api/Dockerfile
                depends_on:
                        - postgres
                        - minio
                environment:
                        - DB_PORT=5432
                        - DB_HOST=postgres
                        - DB_NAME=jira
                        - DB_USER=postgres
                        - DB_PASSWORD=postgres
                ports:
                        - '3001:3001'
                healthcheck:
                        test: ['CMD', 'curl http://localhost:3001/healthz']
                        interval: 1m30s
                        timeout: 30s
                        retries: 5
                        start_period: 30s
                networks:
                        - cache-network
                        - db-network
                        - storage-network
        postgres:
                image: postgres:14.1-alpine
                restart: always
                networks:
                        - db-network
                environment:
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
                        - POSTGRES_DB=jira
                ports:
                        - '5432:5432'
                volumes:
                        - postgres-data:/var/lib/postgresql/data
                healthcheck:
                        test: ['CMD-SHELL', 'pg_isready -d db_prod']
                        interval: 30s
                        timeout: 60s
                        retries: 5
                        start_period: 30s
        minio:
                environment:
                        - MINIO_ROOT_USER=admin
                        - MINIO_ROOT_PASSWORD=admin123
                        - MINIO_DEFAULT_BUCKETS=general,general-test
                image: bitnami/minio
                ports:
                        - '9000:9000'
                        - '9001:9001'
                networks:
                        - storage-network
                volumes:
                        - minio-data:/data
                healthcheck:
                        test:
                                [
                                        'CMD',
                                        'curl',
                                        '-f',
                                        'http://localhost:9000/minio/health/live'
                                ]
                        interval: 30s
                        timeout: 20s
                        retries: 3
                restart: unless-stopped
networks:
        cache-network:
                driver: bridge
        db-network:
                driver: bridge
        storage-network:
                driver: bridge
volumes:
        minio-data:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ${PWD}/data/minio
        postgres-data:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ${PWD}/data/postgresql
